/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary-fixed":              "#d8e2ff",
        "inverse-on-surface":         "#282f49",
        "on-secondary-fixed":         "#111a36",
        "on-secondary-container":     "#abb4d7",
        "secondary-fixed-dim":        "#bdc5e9",
        "tertiary-fixed":             "#ffdbd0",
        "tertiary":                   "#ffb59d",
        "on-primary-fixed-variant":   "#004494",
        "secondary-fixed":            "#dbe1ff",
        "on-error-container":         "#ffdad6",
        "outline-variant":            "#414754",
        "on-tertiary":                "#5d1900",
        "surface-dim":                "#0a122a",
        "on-error":                   "#690005",
        "on-background":              "#dbe1ff",
        "on-primary":                 "#002e69",
        "on-surface":                 "#dbe1ff",
        "on-primary-container":       "#00285d",
        "inverse-surface":            "#dbe1ff",
        "on-tertiary-container":      "#511500",
        "surface-container-high":     "#212942",
        "secondary":                  "#bdc5e9",
        "surface-bright":             "#313852",
        "on-surface-variant":         "#c2c6d6",
        "on-primary-fixed":           "#001a41",
        "primary-container":          "#4c8eff",
        "surface-container-low":      "#131a33",
        "error":                      "#ffb4ab",
        "background":                 "#0a122a",
        "surface-container-highest":  "#2c344d",
        "primary-fixed-dim":          "#adc6ff",
        "outline":                    "#8c909f",
        "secondary-container":        "#3d4664",
        "primary":                    "#adc6ff",
        "surface-tint":               "#adc6ff",
        "error-container":            "#93000a",
        "surface-variant":            "#2c344d",
        "on-tertiary-fixed-variant":  "#832600",
        "tertiary-container":         "#f3632d",
        "surface-container-lowest":   "#050d25",
        "surface-container":          "#171e37",
        "surface":                    "#0a122a",
        "on-tertiary-fixed":          "#390c00",
        "inverse-primary":            "#005ac2",
        "tertiary-fixed-dim":         "#ffb59d",
        "on-secondary-fixed-variant": "#3d4664",
        "on-secondary":               "#262f4c",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        full:    "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body:     ["Manrope",       "sans-serif"],
        label:    ["Space Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [],
}
